version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable security for simplicity in this setup
      - network.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - vdb_network

  databaseservice:
    image: databaseservice
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: databaseservice_container
    command: ["sh", "-c", "python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn vdb_main:app --host 0.0.0.0 --port 8000 --reload"]
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./vdb_app:/vdb_app
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - TIMEOUT=30 #Adjust based on your needs
    depends_on:
      - elasticsearch
    networks:
      - vdb_network
volumes:
  es_data:
    driver: local

networks:
  vdb_network:
    driver: bridge
