
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable security for simplicity in this setup
      - network.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - vdb_network

  databaseservice:
    image: databaseservice
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: databaseservice_container
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - TIMEOUT=30  # Adjust based on your needs
    ports:
      - "80:8000"
    depends_on:
      - elasticsearch
    networks:
      - vdb_network

volumes:
  es_data:
    driver: local

networks:
  vdb_network:
    driver: bridge
